services:
  - mysql
before_script:
  - mysql -u root -e "create database Stack_Double_db;"
  - mysql -u root -e "create user 'TestDB'@'localhost' identified by 'qweasD#123';"
  - mysql -u root -e "grant all privileges on Stack_Double_db. * to 'TestDB'@'localhost';"
language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    master:
      secure: lMlTGY6MhJxE6Tre52beN2uXbtif4PUB84yzU3ZLPT5WBn5ByBP2871eWkCMKydTVIw2jpBvHXuj9S321+XFFi9DeZVWTP3kkCNEcoU3XGLIB/s+CHx1gvz5sf+b0zbjvXxJw3QtyBgfV5znjOjNt0YIAIt+nzSMz0RUY1ulbu3TRvXin4Wku3P0SkaOBy9olz3ihvaHjSpEO+wROxpUtdHuT9npuV9Bl7N+cnYMwyi1nusBE+rYN6SNug2t5bRo5lIazd5fpShy86AG89AD+dTxnoFHhyVBNKgmqN5BQpw6LIhGPLLa+66OuvMW4hp8aT+fPsbR7muejRmnaaIleqJ5+6Tq6srDQyRr8jIE2w4hSbXPJpVLrR0zLkI9Arj6Spekd5g8Yb3rFYtayHz/NjoviSv5wkM65TmUJDxeyyAqoFbjvVBtPMuIsQgFpGz7M/iCc8LmsxTvpGQQnmqVH/2tZ2SzCgSmj64Yph+aDWYjKzbIUkThgXU2rQ+ZEIbuubbO+NPzq5lMmyndIUqwp177muJ8oAmRxDBVU46o3Ps5i/5pqAeAyfX8yYlHhpzd9Xv/XXWFElHOaZFbuN7v7bs8UMNlFtOVoclTLMXW1sfbPD+vITCNQ+Xj0UCP8Rtf4BgnvT9O+b5cTcMGapAp8PQ+VRIW3vMEw29/nBwDPNo=
    deathtest:
      secure: KjhXFa/CN6bbiJFfeAe4+ys8ac6CzapY6LhaqTYmz/NQ8HuZTeGbgw3uWAlhy72UO3z20nqkGS6DczqO3TA3kZSrdPPhs6rTFosVl8TKqIVRW7SlTHoRB6utpzRc814wC1yIfoxKKzRyIRHEjNCg5hpRr140+SrPAM9facwBbCYY7JzEuujqAW12KGYLAUtuTv5biBxDnyv4jC9gDyWuSyMN+ajFFLVjEI5hIKLGHbA84ttafBYop2O3EGhFny9BR2gKNvS0T4uDp/DhvxDAiM91En+TpbqEUPCJs6251GbhqSGM8IvwMO8P5K8hJdsMh+pTJKtpYUYuP7gZ2BkqLb1G9GCgXL9swKQwDLY73nuhODhbW/MOhJ/RCClK9GiDXDNacGPnqrHfiESLmCoXeeDpuRd7Lj0Kc0BeKNZtEStry2Hiz7k7aXG2756n26eT7j/zDi1b0/4p2iatToTGSXLO1i8386dWSeG+5Bm7indcG4dQpFoYwDZqrniLzVBjBvtyFzXDbppDe+BtBvz+A3V0beyGqLV3bk5D2aUisVK/6AUta6vJw9sQE+pE7VndcKiM9bq9bk3ACb3JrLW7B3foK0PfVdxUWbiTH1J++xOm8M2us1vsWs1gK2VNea7uqV/PQjL+aM8XoFYA8o0XL+G0z924uEuKX2Oknwl8fHI=
  app:
    master: card-game-09-2016
    deathtest: cardgame092016
